name: PS5 Mini-Store Automatique

on:
  schedule:
    - cron: '0 */6 * * *' # S'exécute toutes les 6 heures
  workflow_dispatch: # Permet un lancement manuel depuis l'onglet Actions

jobs:
  build-store:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt courant
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-python-version: '3.x'

      - name: Lancement du script de synchronisation globale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python update_store.py

      - name: Commit et Push des fichiers mis à jour
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "PS5 Store Bot"
          git config --global user.email "actions@github.com"
          
          # OPTIMISATION GIT POUR LES GROS ENVOIS (Évite l'erreur 408)
          git config --global http.postBuffer 524288000
          git config --global http.maxRequestSize 524288000
          git config --global ssh.postBuffer 524288000
          
          git add payloads/ json/ README.md rss/
          # On commit uniquement s'il y a des changements pour éviter de faire planter le workflow
          git diff-index --quiet HEAD || git commit -m "[Build Dédié] Synchronisation complète, payloads et JSON mis à jour"
          
          git push origin main
